### ISSUE TITLE
passing log level to thumbor

### ISSUE THREAD

**Issue by fmarani** [APSL/docker-thumbor#1]
I did not find an easy way to pass the log level to the thumbor command line. I think it should be added because it makes debugging easier?

Example: launching the following command, storage is working but result_storage is not. Not sure what's wrong

```
docker run -d --restart=always -p 80:80 -v /home/ubuntu/thumbor/data:/data -v /home/ubuntu/thumbor/logs:/logs -e "RESULT_STORAGE=thumbor.result_storages.file_storage" apsl/thumbor
```

**Comment by eduherraiz** [comment]
I can't test it today, but  I think the problem is by default the result storage is disabled for unsafe. 
Try adding
RESULT_STORAGE_STORES_UNSAFE=True

**Comment by fmarani** [comment]
yep, that solved my immediate problem. Thanks a lot!

**Comment by eduherraiz** [comment]
You are welcome.  It's the normal behavior but I will study increase the log level in the next release. I can't remember if thumbor is able to show this kind of issues. :-)
