### ISSUE TITLE
Error when trying to build the docker image

### ISSUE THREAD

**Issue by tufgupmi** [APSL/docker-thumbor#100]
Hello, 

When i try to build the docker image from thumbor folder i have this errors:

Processing triggers for libc-bin (2.24-11+deb9u3) ...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package python-numpy
E: Unable to locate package python-opencv
E: Unable to locate package git
E: Unable to locate package curl
E: Unable to locate package libdc1394-22
E: Unable to locate package libjpeg-turbo-progs
E: Unable to locate package graphicsmagick
E: Unable to locate package libgraphicsmagick++3
E: Couldn't find any package by regex 'libgraphicsmagick++3
   '
E: Unable to locate package libgraphicsmagick3
E: Unable to locate package libboost-python-dev
E: Version '1.88*
   ' for 'gifsicle' was not found
E: Unable to locate package ffmpeg
The command '/bin/sh -c apt-get update &&     apt-get -y upgrade &&     apt-get -y autoremove &&     xargs apt-get -y -q install < /usr/src/app/system-requirements.txt &&     apt-get clean' returned a non-zero code: 123

**Comment by gingerlime** [comment]
I don't think this project is actively maintained. The docker images on https://github.com/MinimalCompact/thumbor build just fine, so you're welcome to try them if you want.
