### ISSUE TITLE
How much memory is enough to work properly

### ISSUE THREAD

**Issue by singhravi1** [APSL/docker-thumbor#102]
Hello guys,

I'm talking about the multiprocessing docker container here.
I checked the memory used by docker container while **only running without any processing** and it was taking ~400 MB of memory.
My concern is, how much memory should i reserve for the container for running without any problem if i'm aiming more than **1000 requests/sec** and assuming **images to be of size less than 10 MB**?

Thanks

**Comment by gingerlime** [comment]
I saw you posted it also on https://github.com/MinimalCompact/thumbor/issues/22 (and I answered there)
