### ISSUE TITLE
Using Docker-Thumbor with AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by bf** [APSL/docker-thumbor#12]
Hello, and sorry if this is a stupid isse :-)

We have user images uploaded to S3 and want to resize them dynamically using docker-thumbor deployed to an EC2 instance.

For this we deployed the Dockerrun.aws.json to AWS Elastic Beanstalk to dynamically resize the user profile images stored in an S3 bucket:

`{
  "AWSEBDockerrunVersion": "1",
  "Image": {
    "Name": "apsl/thumbor"
  },
 "Ports": [
    {
      "ContainerPort": "8000"
    }
  ]
}`

The Thumbor Docker image is pulled by the Beanstalk instance from https://hub.docker.com/r/apsl/thumbor/ by AWS, and we give it the TC_AWS_LOADER_BUCKET='foocompany-images' environment variable, where `foocompany-images` is the name of the S3 bucket.

I expected the url `.../unsafe/100x100/foocompany-images/existingimage.jpg` to work with this setting, but it always gives a 404. Unfortunately the instance logs don't give any indication that Thumbor tries to access S3 or that the TC_AWS_ setting is applied at all.

Our Thumbor docker container works with the example URL where an image is fetched and resized from imgur.

Could it be that TC_AWS_XXX is not activated in the base image?

**Comment by bf** [comment]
To give more info, here is the log I see:

```
2016-03-01 11:53:36 thumbor:WARNING ERROR retrieving image http://foocompany-images/001d91eb-fc35-4fad-a6b0-4bf94eb43f5e.jpg: [Errno -2] Name or service not known
2016-03-01 11:53:36 tornado.access:WARNING 404 GET /unsafe/50x50/foocompany-images/001d91eb-fc35-4fad-a6b0-4bf94eb43f5e.jpg (172.17.0.1) 3.43ms
```

**Comment by bf** [comment]
I also see in issue https://github.com/thumbor/thumbor/issues/529 that others are using thumbor with the full URL to the S3 bucket, which also works for me. I just expected that giving the `TC_AWS_LOADER_BUCKET` setting allows direct fetching from S3 by using bucket and image name, otherwise it wouldn't make sense to have a `TC_AWS_LOADER_BUCKET` setting at all.

**Comment by eduherraiz** [comment]
Take a look in the working docker-compose example to view what variables do you need: https://github.com/APSL/docker-thumbor/blob/master/docker-compose-examples/aws-s3-storage.yml

**Comment by bf** [comment]
Thanks eduherraiz, it was not clear from the docs that you need all these params. I got it working until a new error with the following config:

```
AWS_ACCESS_KEY_ID = XXX
AWS_SECRET_ACCESS_KEY = XXX
LOADER = tc_aws.loaders.s3_loader
TC_AWS_LOADER_BUCKET = my-bucket-name
```

Unfortunately it still crashes with error `2016-03-01 13:57:52 thumbor:WARNING ERROR retrieving image from S3 001d91eb-fc35-4fad-a6b0-4bf94eb43f5e.jpg: {'ResponseMetadata': {'HTTPStatusCode': 400, 'HostId': 'REDACTED', 'RequestId': '1AE2D8'}, 'Error': {'Message': 'The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.', 'Code': 'InvalidRequest'}}`.

This means that the thumbor plugin is using outdated authorization method (version 2) when trying to connect to AWS. All new AWS regions are exclusively using version 4. This can only be solved by updating the AWS SDK that is being used in thumbor or its dependency to do the aws auth.

Plese also see issue: https://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4/26538266

Is this something you guys can fix?

**Comment by eduherraiz** [comment]
I think the problem is in boto:
https://github.com/boto/boto/issues/2741

Try including another env var:

```
S3_USE_SIGV4 = True
```

**Comment by bf** [comment]
I tried it with the env var and unfortunately I didn't work. I think thumbor is using an outdated version of boto?

**Comment by bf** [comment]
@eduherraiz I am delighted to tell you that the issue was solved. The following environment parameters need to be set for thumbor to load images from S3.

```
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
LOADER=tc_aws.loaders.s3_loader
S3_USE_SIGV4=True
TC_AWS_LOADER_BUCKET=bucket-name
TC_AWS_REGION=eu-central-1

```

**Comment by eduherraiz** [comment]
@bf Great! Glad to help. 
Could you share your final working json configuration (without secrets) to include it here?
I will include more examples ready to use in kubernetes, and if you share it, also Beanstalk.

**Comment by bf** [comment]
For AWS Beanstalk you need to create a `Dockerun.aws.json` file with the following contents. Create a new Beanstalk environment and simply upload the JSON file. 

```
{
  "AWSEBDockerrunVersion": "1",
  "Image": {
    "Name": "apsl/thumbor"
  },
 "Ports": [
    {
      "ContainerPort": "8000"
    }
  ]
}
```

As soon as the new environment is booted, you need to go to the configuration section where you can set the environment parameters for the docker container. There you should define the following environment variables to serve files from your AWS S3 Bucket through thumbor to your users (all environment params are listed on https://hub.docker.com/r/apsl/thumbor/ ).

```
AWS_ACCESS_KEY_ID=XXXXXX
AWS_SECRET_ACCESS_KEY=XXXXXX
LOADER=tc_aws.loaders.s3_loader
S3_USE_SIGV4=True
TC_AWS_LOADER_BUCKET=bucket-name
TC_AWS_REGION=eu-central-1
```

If you want to store the files resized by thumbor on S3 as well, you need to add some more evironment params. We use a caching server in front of thumbor which solves the need for caching of result files in S3.

**Comment by eduherraiz** [comment]
Thank you!

**Comment by jjborie** [comment]
You can add your env directly on the json:

```

      "environment": [
        {
          "name": "Container",
          "value": "thumbor"
        },
        {
          "name": "SECURITY_KEY",
          "value": "my key is secured"
        },
        {
          "name": "DETECTORS",
          "value": "['thumbor.detectors.queued_detector.queued_complete_detector',]"
        },
etc...
```

**Comment by bf** [comment]
Thanks for the info, but I prefer that our team has transparence into the configuration params of our running instances from within AWS. This also makes it easier to respond to change requests without having to redeploy the whole cluster - we only have to change the config and AWS takes it from there.
