### ISSUE TITLE
Thumbor S3 not working with Frankfurt Servers requiring API v4

### ISSUE THREAD

**Issue by emazzotta** [APSL/docker-thumbor#13]
I successfully had an image generated by thumbor on our amazon machine but it doesn't get uploaded to S3 due to this error:

`thumbor_1 | 2016-03-16 10:05:22 thumbor:WARNING [STORAGE] error occured while storing data: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.`

This is likely due to our infrastructure being in Frankfurt which was rolled out after 2014 and thus requires a new authentication mechanism.

The S3 key and secret I generated work fine.

Could this please be implemented?

**Comment by eduherraiz** [comment]
I think is the same case of this issue: #12 
Could you try with the extra env vars that were commented?

**Comment by emazzotta** [comment]
Yes, correct. Thanks!

The missing env vars were:

```
S3_USE_SIGV4: true
TC_AWS_REGION: eu-central-1
```

I will add those to the yml examples in a commented state and open a pull request to make it easier for people to find the solution if they have this issue in the future :)

**Comment by bf** [comment]
What a mess this thumbor configuration is. Suddenly `true` needs to be written `true` and must not be `True` because it wouldn't apply the option. Holy.
