### ISSUE TITLE
Volume creation does not work

### ISSUE THREAD

**Issue by woody3549** [APSL/docker-thumbor#16]
With latest build, logs folder is not creating log file to local volume.
Current docker-compose file contains:
thumbor:
  image: apsl/thumbor-multiprocess:5.2.1c
  volumes:
    - "./data:/data"
    - "./logs:/logs"

**Comment by eduherraiz** [comment]
We change the log out to the standard in docker systems: STDOUT.
https://docs.docker.com/engine/reference/commandline/logs/
The docker engine or the orchestator you use can manage the logs. The volume log is deprecated.
We will remove the logs volume in the next release.
Sorry about the inconvenience.

**Comment by eduherraiz** [comment]
Fixed in release 6.0.1
