### ISSUE TITLE
Newrelic support

### ISSUE THREAD

**Issue by dijam** [APSL/docker-thumbor#21]
Do you have any plan to add newrelic support? 
So it installs newrelic-sysmond and accepts license key via env variables.

**Comment by eduherraiz** [comment]
There is not any plan to support it, it's not a feature any user use by default.
We are trying to mantain the original image as small as possible. 
Maybe you can do it building a new docker image, extending the original apsl/thumbor and installing all you need it for monitor, like we are doing in thumbor-multiprocess image.
