### ISSUE TITLE
The docker container has insufficient SSL certificates

### ISSUE THREAD

**Issue by hus787** [APSL/docker-thumbor#27]
As of 6.0.1, the SSL certificates available to thumbor inside the container are insufficient to fetch some of the ssl based images (urls below). Bashing into the container and curl complains about not found certificates.

**Curl:**

``` shell
root@deb08d83e7dc:~# curl  https://static01.nyt.com/images/2016/05/24/world/24FINLAND-web1/24FINLAND0-web1-superJumbo.jpg > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Thumbor(** `http://192.168.99.100:8000/unsafe/300x200/smart/https%3A%2F%2Fstatic01.nyt.com%2Fimages%2F2016%2F05%2F24%2Fworld%2F24FINLAND-web1%2F24FINLAND0-web1-superJumbo.jpg`**):**

```
2016-05-31 12:07:14 tornado.general:WARNING SSL Error on 8 ('23.37.97.37', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
2016-05-31 12:07:14 thumbor:WARNING ERROR retrieving image https://static01.nyt.com/images/2016/05/24/world/24FINLAND-web1/24FINLAND0-web1-superJumbo.jpg : [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
2016-05-31 12:07:14 tornado.access:ERROR 504 GET /unsafe/300x200/smart/https%3A%2F%2Fstatic01.nyt.com%2Fimages%2F2016%2F05%2F24%2Fworld%2F24FINLAND-web1%2F24FINLAND0-web1-superJumbo.jpg%20 (192.168.99.1) 58.22ms
```

If [this](http://certifie.com/ca-bundle/ca-bundle.crt.txt) cert bundle from [here](http://certifie.com/ca-bundle/) is used with `--cacert` it is able to fetch. (Not sure if adding that explicitly to the docker build file would be good idea.)

Image urls:
- https://static01.nyt.com/images/2016/05/24/world/24FINLAND-web1/24FINLAND0-web1-superJumbo.jpg 
- https://assets.kpmg.com/content/dam/kpmg/images/2016/03/gr-compben-retail-121875.jpg/jcr:content/renditions/cq5dam.web.512.341.jpg

**Comment by eduherraiz** [comment]
I think is a problem with the remote server that don't have the certificate correctly installed. 
Maybe is not a good idea include this certificates in the build but I will reconsider it if someone prepare a Pull Request.

**Comment by hus787** [comment]
I think it's the other way round. The client has an incomplete set of certificates. E.g. the images can be fetched with a mint Ubuntu.

**Comment by hus787** [comment]
It was the Python image that was outdated. Rebuilding the docker fixed the problem.
