### ISSUE TITLE
Missing MAX_PIXELS config in thumbor.conf.tpl

### ISSUE THREAD

**Issue by cerber717** [APSL/docker-thumbor#31]
I am getting en error when I am trying to process extra large images. Thumbor has the config to change it  but APSL/docker-thumbor does not have into its thumbor/conf/thumbor.conf.tpl 

I added it here is the PR - https://github.com/APSL/docker-thumbor/pull/30

**Comment by eduherraiz** [comment]
Included in the new version: 6.0.2
Thank you @cerber717 !!
