### ISSUE TITLE
thumbor-multiprocess missing configs from #29 and #30

### ISSUE THREAD

**Issue by kkopachev** [APSL/docker-thumbor#34]
Pulled fresh thumbor-multiprocess and looks like it's missing MAX_PIXELS and REDIS_\* config variables which was merged in #29 and #30

**Comment by eduherraiz** [comment]
I will review the merge tomorrow. Possibly my mistake.

**Comment by eduherraiz** [comment]
In the last review I included a error in the last step pushing the image.
Fixed here: https://github.com/APSL/docker-thumbor/commit/c0619af4ca6c4694b5faa73bc7a9bd09d5218545

The image is correctly pushed now and we can see the new env vars correctly.
Enjoy! :-D
