### ISSUE TITLE
Change to the offcial aws extension

### ISSUE THREAD

**Issue by eduherraiz** [APSL/docker-thumbor#4]
Need to change the aws extension to the official:
https://github.com/thumbor-community/aws

**Comment by frankier** [comment]
Particularly since the s3 loader is incompatible with the version of docker used here

**Comment by eduherraiz** [comment]
This enhancement is blocked for a problem found in the aws offcial extension:
https://github.com/thumbor-community/aws/issues/45

**Comment by eduherraiz** [comment]
The problem is solved and the tc_aws branch is ready to merge to master.
Planned to merge in master in the next release.

**Comment by eduherraiz** [comment]
New release 5.2.1b with this issue fixed.
