### ISSUE TITLE
Support for gifv (depends on ffmpeg binary)

### ISSUE THREAD

**Issue by designgrill** [APSL/docker-thumbor#40]
Thumbor supports using [ffmpeg to convert animated gifs to video](https://github.com/thumbor/thumbor/commit/159c0b47557a20683384111ea4093d5e7f355de3) via inbuilt gifv optimizer. I hope adding ffmpeg binary to this docker image is sufficient to make the gifv filter work.

**Comment by eduherraiz** [comment]
I did the work in the new version 6.1.3 : https://github.com/APSL/docker-thumbor/compare/6.1.3?expand=1

It's not merged to master, but it's a new fresh tag 6.1.3 in the registry: https://hub.docker.com/r/apsl/thumbor/tags/

Could you test the ffmpeg with thumbor using this new tag?

**Comment by designgrill** [comment]
Thanks @eduherraiz! It was quick and works perfectly. 👍

I hope it finds its way soon in the master as well.

**Comment by eduherraiz** [comment]
Merged in 6.1.5
