### ISSUE TITLE
Env vars for docker

### ISSUE THREAD

**Issue by Alex-query** [APSL/docker-thumbor#47]
sudo docker run -e UPLOAD_ENABLED=True -e DETECTORS=['"thumbor.detectors.feature_detector"'] -p 8003:8000 apsl/thumbor
Quote very important, else you will have error "NameError: name 'thumbor' is not defined"

**Comment by eduherraiz** [comment]
This is a problem with docker run and I will consider include a entry in documentation.
I recommend you use docker-compose

**Comment by konradreiche** [comment]
This works using the following syntax:
```
--env=DETECTORS="['thumbor.detectors.face_detector','thumbor.detectors.feature_detector']"
```
