### ISSUE TITLE
Ability to configure SEND_IF_MODIFIED_LAST_MODIFIED_HEADERS

### ISSUE THREAD

**Issue by a5hay** [APSL/docker-thumbor#52]
This is more like a feature request than a bug. 
If you check https://github.com/thumbor/thumbor/blob/master/debian/thumbor.conf you will see that thumbor has the ability to set SEND_IF_MODIFIED_LAST_MODIFIED_HEADERS. Can we also have this option in the thumbor.conf.tpl in this project so that we can set this to True if needed?

**Comment by eduherraiz** [comment]
Of course. I will include this in the next release.

**Comment by a5hay** [comment]
Thanks! -- Looking forward to the next release

**Comment by eduherraiz** [comment]
Included in 6.2.0 image. It's not latest, but is pushed in docker hub. 
Could you test it?

**Comment by a5hay** [comment]
Sure -- I can and send my update

**Comment by a5hay** [comment]
Thanks a lot btw! :)
