### ISSUE TITLE
Can't load images using `tc_aws.loaders.s3_loader`

### ISSUE THREAD

**Issue by arthens** [APSL/docker-thumbor#55]
I'm using https://github.com/APSL/docker-thumbor with tc_aws.loaders.s3_loader, but I can't seem to get it to work. The error I'm getting is:

```
2016-11-22 09:26:57 thumbor:ERROR [BaseHandler] get_image failed for url `bucket-name/design-example-1.jpg`. error: `Parameter validation failed:
Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$"`
2016-11-22 09:26:57 tornado.access:ERROR 500 GET /PbhAZkbZdM0Q5AWPztSfaFdalNY=/fit-in/500x500/bucket-name/design-example-1.jpg (172.31.1.220) 39.45ms
```

which seems to imply that it's failing to extract the bucket name from my url... is the url I'm generating wrong or is this a bug/configuration problem?

This is the configuration I'm using:

```
MAX_WIDTH=2000
MAX_HEIGHT=2000
SECURITY_KEY='****'
ALLOW_UNSAFE_URL=False
LOADER='tc_aws.loaders.s3_loader'
STORAGE='thumbor.storages.no_storage'
RESULT_STORAGE='tc_aws.result_storages.s3_storage'
AWS_ACCESS_KEY_ID='****'
AWS_SECRET_ACCESS_KEY='****'
TC_AWS_REGION='eu-west-1'
TC_AWS_RESULT_STORAGE_BUCKET='another-bucket-name'
TC_AWS_RESULT_STORAGE_ROOT_PATH=''
TC_AWS_MAX_RETRY=3
TC_AWS_STORAGE_SSE=False
TC_AWS_STORAGE_RRS=True
TC_AWS_ENABLE_HTTP_LOADER=False
TC_AWS_ALLOWED_BUCKETS=False
TC_AWS_STORE_METADATA=False
```

Thanks

**Comment by eduherraiz** [comment]
I think you need to define TC_AWS_LOADER_BUCKET
Take a look this docker-compose example: 
https://github.com/APSL/docker-thumbor/blob/master/configuration_examples/docker-compose/aws-s3-storage.yml

**Comment by arthens** [comment]
Maybe I'm misreading the `s3_loader` code, but it seems to me that it should be able to handle reading the bucket from the url? https://github.com/thumbor-community/aws/blob/master/tc_aws/loaders/__init__.py#L21

The reason I'm not using `TC_AWS_LOADER_BUCKET` is that I have at least 2 buckets I need to resize images from

**Comment by eduherraiz** [comment]
I can't say, I never used this way...
Maybe you should force TC_AWS_LOADER_BUCKET to None. The default value is:
https://github.com/APSL/docker-thumbor/blob/master/thumbor/conf/thumbor.conf.tpl#L635

**Comment by JensVerneuer** [comment]
I also had problems with providing the bucket name in url, without big investigation I solved it by just jusing folders (prefixes) for the different projects. That works fine and there is no need to adjust the IAM role which restricts thumbor to a specific bucket when adding a project. 
Deployed on Beanstalk it serves now roughly a year without issues. 
With CloudFront and a nice cname on top it looks like this:
https://cdn.voyagesdetective.fr/340x0/filters:quality(100)/voyagesdetective/2016/08/logo-horizontal-web-cuted.png

/voyagesdetective/ is the s3 folder in the shared bucket here.

I hope this helps getting it rolling for you.

**Comment by arthens** [comment]
> Maybe you should force TC_AWS_LOADER_BUCKET to None.

That was it! Thank you very much

**Comment by eduherraiz** [comment]
You are welcome!
