### ISSUE TITLE
Possible to use newer botocore?

### ISSUE THREAD

**Issue by kkopachev** [APSL/docker-thumbor#57]
Hi! 

We're using AWS ECS to run thumbor. In ECS it is possible to configure Task Role for a container, so AWS SDK inside container can automatically figure out credentials to use, so it won't be necessary to pass credentials via env vars or to put credentials file inside container.
Unfortunately, minimum version of botocore should be [1.4.37](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html#task-iam-roles-minimum-sdk).
So, is it possible to upgrade to newer botocore?

**Comment by eduherraiz** [comment]
Of course, I'll try in the next release.

**Comment by kkopachev** [comment]
Well, I tried to update it in Dockerfile, built successfully, but does not work - there are some incompatibilities with thumbor-aws. 
I'll try to look into upgrading that next year (I hope).

However, I don't fully understand why do you use custom pinned version of botocore?

**Comment by eduherraiz** [comment]
We pinned the version to fix a problem with special chars using thumbor_aws in s3:
https://github.com/APSL/botocore/commit/5e284735fc54ec8aadc31b9f8fffad2f84b134e4

**Comment by kkopachev** [comment]
Thanks for explanation. I also found out that tornado_botocore also have pinned botocore pinned to 1.2.0, and probably there is no easy way to upgrade.

**Comment by jonatasalves-hotmart** [comment]
Hi, Same case here. Any news?
