### ISSUE TITLE
Remotecv file loader?

### ISSUE THREAD

**Issue by janslu** [APSL/docker-thumbor#59]
I want to install thumbor as an image resizer / thumbnailer for a website hosted on a local server. I have access to all images locally and I don't need to use http loader for them. I tried the following  thumbor settings: 
```
volumes: 
   - "/var/www/fileadmin:/var/srv/fileadmin"
envs:
   - LOADER=thumbor.loaders.file_loader
   - FILE_LOADER_ROOT_PATH=/var/srv
```

but remotecv doesn't seem to have file_loader mechanism and errors out with image not found... 
Is there any benefit in using remotecv in my scenario or should I just rely on thumbor "direct" detectors? Or am I missing a setting in remotecv?

**Comment by eduherraiz** [comment]
I never used remotecv with file_loader and I can see is not implemented.
You can implement your custom remotevc loader for this case, but I think remotecv it's not necessary. You only win time for the first request, and if your image detection it's not very slow you should consider simplify and remove remotecv.

And seems remotecv it's not continued, for example, we have a pull request opened 6 months ago: https://github.com/thumbor/remotecv/pull/14 , without any new.
