### ISSUE TITLE
Please consider upgrading to Thumbor 6.2.1

### ISSUE THREAD

**Issue by ghost** [APSL/docker-thumbor#60]
There is an issue with using AWS for results storage on 6.2.0 for GIFv, at least.

See: https://github.com/thumbor/thumbor/issues/848
And: https://github.com/thumbor-community/aws/issues/86

**Comment by ghost** [comment]
PR here https://github.com/APSL/docker-thumbor/pull/62

**Comment by eduherraiz** [comment]
Thumbor upgraded in apsl/thumbor:6.2.1 
thumbor==6.2.1
tc-aws==6.0.2

It's not latest yet, but it's ready in docker hub.
