### ISSUE TITLE
How to build and contribute?

### ISSUE THREAD

**Issue by ghost** [APSL/docker-thumbor#61]
You have a customized build process which is not documented. It would be helpful to share the process you use for development so that others can more easily contribute.

Thanks

**Comment by eduherraiz** [comment]
I know it's really necessary a documentation to open contributions. 
I'm happy you want to help, I will be do an effort to explain how we did the work.

**Comment by DominikAngerer** [comment]
Hey @eduherraiz would really appreciate some hints or even the documentation to rebuild the whole docker image - currently we can't get it running with some changes we made as shown here: https://github.com/thumbor/thumbor/issues/868

Thanks

**Comment by eduherraiz** [comment]
### "Grosso modo"
Take a look how the continous integration make the work: https://github.com/APSL/docker-thumbor/blob/master/.travis.yml

1. All the build process could be done by the **builder** script in root path that use docker-compose
2. The build process have initial step that archive the python dependencies in wheels. This dependencies are share in the other containers and we save build them in every step. We use a wheel server pypiserver to install the wheels in the build process of the other containers (avoiding copy the wheels inside the container). You have to change the version in build-requirements.txt . And in the requirements.txt of the thumbor image use the tag version builded, not the real reference to github.
3. After the build we use the same process to tag the images, but this is step is not necessary in your case.

But....., Did you consider build a custom image from original builded apsl/thumbor?
Something like:
```
FROM apsl/thumbor
RUN pip uninstall thumbor
RUN pip install my_thumbor_version --upgrade
```

By the way, I'm thinking about to refactor all the process with a different aproach in a near future, doing a thumbor-base image with all the system-dependencies and shared python libs. The final thumbor images will extend thumbor-base to install a particular version of thumbor or other custom installations.

**Comment by beenanner** [comment]
@eduherraiz let me know if you need or would like any help I'd be happy to get involved with the refactoring for testing / etc. I have been absent for a while, but would like to circle back around on #41, but maybe that will be stomped out by the refactoring mentioned above. :-)

**Comment by onefriendaday** [comment]
Building a custom image with the following commands worked for me:

```
FROM apsl/thumbor
RUN pip uninstall -y thumbor; true;
RUN pip install my_thumbor_version --upgrade
```
