### ISSUE TITLE
Graceful monoprocess restart

### ISSUE THREAD

**Issue by leandro** [APSL/docker-thumbor#64]
First of all, sorry for asking this as an issue but I couldn't find anywhere else to ask this kind of question.

So, how can I graceful restart my docker container (and thumbor as consequence) in a way it gets my recently updated environment variables (from a file) before it restarts thumbor and the container itself?

I'm running it in production (in a small project so far) with something like:
`docker run --env-file conf/docker-thumbor-vars.env ...`

The thing is I want to update some Thumbor configuration variables and cause 0s downtime.

**Comment by eduherraiz** [comment]
This is not a issue of docker-thumbor. 
Using docker you have to look about blue-green deployments, but it's necessary a new image for a balancer. For example: https://blog.tutum.co/2015/06/08/blue-green-deployment-using-containers/
