### ISSUE TITLE
Ability to extend config.tpl

### ISSUE THREAD

**Issue by kkopachev** [APSL/docker-thumbor#66]
Would be nice to have an optional file which will extend current thumbor.conf.tpl - e.g. providing new config parameters. That's useful in case when using thumbor-plugins which define more config options. Currently I have to copy whole thumbor.conf.tpl, add new parameters to the end and `ADD` it in my Dockerfile. That works well, but with new releases of docker images I have to go back to this repo and grab latest conf file and reinsert my custom parameters again.

**Comment by spantaleev** [comment]
Today I found the need for another option (which this image does not handle), so I also had to do something similar.

Instead of overriding the whole `thumbor.conf.tpl`, however, you could probably do something less fragile, like:

    FROM apsl/thumbor:6.2.1

    RUN echo "CUSTOM_THING = '{{ CUSTOM_THING | default('') }}'" >> /usr/src/app/thumbor.conf.tpl

**Comment by kkopachev** [comment]
Awesome! Thanks!
