### ISSUE TITLE
EXPOSE 80 ?

### ISSUE THREAD

**Issue by gytisgreitai** [APSL/docker-thumbor#74]
Hi,
the README states:
`The thumbor's docker expose port 8000 with the service.`

If i run the image i see that thumbor is listening on 8000:
`tcp        0      0 0.0.0.0:8000            0.0.0.0:*`

But if I look at the Dockerfile on docker hub https://hub.docker.com/r/apsl/thumbor/~/dockerfile/ I see:

`EXPOSE 80`

Is this intentional?

**Comment by eduherraiz** [comment]
Sorry, the information in hub is outdated. The hub import the README the first time, but not the changes.

**Comment by eduherraiz** [comment]
I tried but is not possible change the Dockerfile in the hub. :-(
