### ISSUE TITLE
Update nginx base image

### ISSUE THREAD

**Issue by mijamo** [APSL/docker-thumbor#77]
Would it be possible to update the nginx base image to 1.13? One of the benefits is that 1.13 Docker version is finally compatible with HTTP/2 on most browsers whereas 1.11 is stuck with HTTP/1.1 in Chrome.

I am not aware of any potential problem updating 1.11 to 1.13.

**Comment by zoidyzoidzoid** [comment]
@mijamo Maybe make a PR updating the [`Dockerfile`](https://github.com/APSL/docker-thumbor/blob/master/nginx/Dockerfile) to 1.13?

**Comment by zoidyzoidzoid** [comment]
So the nginx on the image with the `6.3.0` tag on Docker Hub is using 1.13: https://hub.docker.com/r/apsl/thumbor-nginx/tags/

**Comment by zoidyzoidzoid** [comment]
```
docker run -it apsl/thumbor-nginx:6.3.0 -- nginx -v
Configuring nginx: Disabling CORS
Configuring nginx: Disabling Content-Disposition
Configuring nginx: Enabling WEBP
nginx version: nginx/1.13.0
```

**Comment by mijamo** [comment]
Interesting, how is it possible with the Dockerfile still being on 1.11? Anyway I will make a small PR then :)

**Comment by mijamo** [comment]
It also seems like 6.3.0 is weird/broken, it weight 55MB vs 71MB for the previous versions and nginx just exists. It also seems like in general the Docker tags does not correspond to the branches of this repo. 

Is that normal?

**Comment by zoidyzoidzoid** [comment]
I think the builds on Docker Hub might be coming from some private repo they have, and this repo is some sort of out of date mirror.

The newer nginx image works for me, however there were some changes in the entrypoint that I had to account for in our entrypoint that we run before theirs.

**Comment by eduherraiz** [comment]
The new work on 6.7.5 branch will close this.
