### ISSUE TITLE
Thumbor 6.4 version upgrade

### ISSUE THREAD

**Issue by gytisgreitai** [APSL/docker-thumbor#79]
Hi,

would it be possible to bump to 6.3.2 ?

**Comment by gingerlime** [comment]
or 6.4 ?? :)

**Comment by eduherraiz** [comment]
I think upgrade to 6.4  is the best option now.
I have some ideas to change the build process and images hierarchy.
I will work on the new version this week, but maybe is a long job because:

- The new version thumbor version have a lot of changes we need to review
- I can see we need a thumbor-base image and extend it to install the custom versions dependencies.
- Refactor the build process to manage thumbor-base

**Comment by gingerlime** [comment]
I created a PR for 6.4, but simply updated 6.3 -> 6.4 wherever I saw it. Happy to help if I can, but would be great to have a reliable docker image for thumbor that keeps in sync with the latest release.

**Comment by gingerlime** [comment]
Any updates on this one? would be great to have the latest version available via docker

**Comment by nhapke** [comment]
@eduherraiz , would be great to get https://github.com/APSL/docker-thumbor/pull/87 merged. Anything we can help with to get this done? 

It is currently blocking some improvements and we would like to avoid forking.

**Comment by eduherraiz** [comment]
Start the job on branch 6.4.2.
We have a new tag on docker hub -> apsl/thumbor:6.4.2
Initially we just pin the new version but we will need to review:
- [ ] Use python3. New thumbor allow now python3 and we should change it for perfomance and security.
- [ ] Change the build process. Move all the image shared dependencies to new thumbor-base image and refactor the way to build, doing the other images (remotecv, simd, etc) from thumbor-base. 
- [ ] Test replace bash build script with "Makefile" system. 
- [ ] Test change the original thumbor-base image (now is python official) for smaller one, like alpine or [phusion](http://phusion.github.io/baseimage-docker/). The thumbor docker images are really big and we need to slim down it. Maybe we don't win nothing or is not possible but we have to check.
- [ ] Add the new thumbor configuration variables available in conf and env vars templating.
- [ ] Upgrade the python dependencies (requirements.txt) that have new version available.

I will review and accept PR changes in order to get this checklist completed before release the new 'latest' version tag. I'm open to discuss this plan and I'll be happy to hear new proposals.
I hope we can create a developing group and will add external mantainers to don't get the repository abandoned.
cc: @shaneog @gingerlime @nhapke @gytisgreitai

**Comment by gingerlime** [comment]
Thanks a lot @eduherraiz.

Not sure how related, but after upgrading to use the 6.4.2 tag, I started seeing these errors (similar to https://github.com/thumbor/thumbor/issues/1045)

```
thumbor_1      | 2018-04-11 13:14:43 thumbor:ERROR ERROR: Traceback (most recent call last):
thumbor_1      |   File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 153, in get_image
thumbor_1      |     self.context.request.image_url
thumbor_1      |   File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
thumbor_1      |     value = future.result()
thumbor_1      |   File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
thumbor_1      |     raise_exc_info(self._exc_info)
thumbor_1      |   File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
thumbor_1      |     yielded = self.gen.send(value)
thumbor_1      |   File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 580, in _fetch
thumbor_1      |     loader_result = yield self.context.modules.loader.load(self.context, url)
thumbor_1      |   File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 483, in wrapper
thumbor_1      |     future.result()
thumbor_1      |   File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
thumbor_1      |     raise_exc_info(self._exc_info)
thumbor_1      |   File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 471, in wrapper
thumbor_1      |     result = f(*args, **kwargs)
thumbor_1      |   File "/usr/local/lib/python2.7/site-packages/tc_aws/loaders/s3_loader.py", line 49, in load
thumbor_1      |     bucket_loader.get(key, callback=handle_data)
thumbor_1      |   File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 483, in wrapper
thumbor_1      |     future.result()
thumbor_1      |   File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
thumbor_1      |     raise_exc_info(self._exc_info)
thumbor_1      |   File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 471, in wrapper
thumbor_1      |     result = f(*args, **kwargs)
thumbor_1      |   File "/usr/local/lib/python2.7/site-packages/tc_aws/aws/bucket.py", line 48, in get
thumbor_1      |     Key=self._clean_key(path),
thumbor_1      |   File "/usr/local/lib/python2.7/site-packages/tornado_botocore/base.py", line 157, in call
thumbor_1      |     callback=callback
thumbor_1      |   File "/usr/local/lib/python2.7/site-packages/tornado_botocore/base.py", line 109, in _make_api_call
thumbor_1      |     request_dict = self.client._convert_to_request_dict(api_params, operation_model, {})
thumbor_1      | TypeError: _convert_to_request_dict() takes exactly 3 arguments (4 given)
```

Anybody bumped into this? I can also create a separate ticket, but maybe others who upgraded recently can comment?

**Comment by eerootsus** [comment]
@gingerlime Yes - botocore needs to be updated
https://github.com/eerootsus/docker-thumbor/commit/de2b03485c5b7bf6cb4c5121cad95c38f907e1b6

**Comment by gingerlime** [comment]
@eerootsus would you mind creating a PR for this project? (in general, I wonder if you are interesting in contributing to this project, or do you prefer promote your own as an alternative? I don't mean it in a negative way, but just curious)

**Comment by eerootsus** [comment]
@gingerlime No, I'm not planning to promote my own version - I just needed some features in 6.4 and had to create my own version to move on. When this repository gets updates I'll surely move back.

I'll do a PR then.

**Comment by gingerlime** [comment]
@eduherraiz

> Use python3. New thumbor allow now python3 and we should change it for perfomance and security.

I don't think Thumbor officially supports python3 yet (see https://github.com/thumbor/thumbor/issues/1004). In fact, I tried to create a docker container using Python 3, and then immediately bumped into this problem just trying to start it https://github.com/thumbor/thumbor/issues/1035

I was thinking of trying to work on the base image using python3, but I guess we should continue with python2 for now. 

Besides that, it looks like this project is stuck again? I'm still waiting for #92 but it's open for nearly a month without being merged or any feedback from you. If you don't have time for this project, @eduherraiz that's totally understandable, but then maybe appoint someone else as a contributor who can move things forward? Or perhaps the community can move forward with a fork of this project that will be a recommended successor? I think there are several contributors like @eerootsus , @kkopachev or others who might be interested?

**Comment by bagipriyank** [comment]
any update on this?

**Comment by LRancez** [comment]
Thumbor is on version 6.5.1 already. Please update the docker.

**Comment by gingerlime** [comment]
I'd be happy to, but there's no update from @eduherraiz unfortunately.

**Comment by gytisgreitai** [comment]
I've just created my own based on this https://github.com/NYTimes/thumbor-docker-image and this https://github.com/julianbei/alpine-opencv-microimage

**Comment by drzraf** [comment]
That's probably the right direction, but the nice thing to borrow from `apsl/docker-thumbor` is configuration template which allow passing **array-variable** from **environment** (what is [not possible](https://github.com/thumbor/thumbor/blob/master/docs/configuration.rst#override-config-through-environment-variable) with `thumblor --use-environment`)

**Comment by gytisgreitai** [comment]
for me - not an issue. Since we are using it on kubernetes,  I've just mapped whole config via config map

**Comment by cameronbraid** [comment]
@gytisgreitai are you able to share your build ?  I hacked together something quickly from python:2.7.15-stretch but if you have something that produces a smaller image that sounds ideal

```
FROM python:2.7.15-stretch
RUN pip --no-cache-dir install thumbor
ADD thumbor.conf /etc/thumbor.conf
ENTRYPOINT ["/usr/local/bin/thumbor", "--port=8000"]
EXPOSE 8000
```

**Comment by gytisgreitai** [comment]
It is anything but small (470mb) cause of opencv, and we have additional libs like cairosvg, and google cloud original storage etc. right now it's on private repo (github cloud). so not sure if you're still interested

**Comment by gingerlime** [comment]
Take a look at https://github.com/MinimalCompact/thumbor

It's a loose fork, using a simpler image structure, nginx-proxy, and supports up to latest version of thumbor (6.5.1).

**Comment by sibelius** [comment]
any improvement on this?

**Comment by gingerlime** [comment]
https://github.com/MinimalCompact/thumbor keeps up-to-date with thumbor
