### ISSUE TITLE
Warning message about favicon.ico

### ISSUE THREAD

**Issue by mfilotto** [APSL/docker-thumbor#8]
Hi,
I'm keep having these error messages at each request

```
tornado.access:WARNING 400 GET /favicon.ico (192.168.99.1) 2.51ms
thumbor:WARNING URL does not have hash or unsafe, or has both: /favicon.ico
```

Any idea ?

**Comment by jjborie** [comment]
Hi,

Just change the path of your favicon on you html page.
It's useless to use thumbor for it I think.
`
<link rel="icon" href="/otherpaththanthumbor/favicon.ico' }}" type="image/x-icon" />
`

**Comment by eduherraiz** [comment]
It's a problem when you check thumbor URL in a browser directly. 
Your browser search a image favicon.ico and the request arrive to thumbor. 
We mitigate it in thumbor-nginx, but I think it's not possible to solve it directly.

**Comment by mfilotto** [comment]
@eduherraiz It's my use case indeed
Thanks
