### ISSUE TITLE
If AUTO_WEBP option is enabled all cors header are not emitted by nginx

### ISSUE THREAD

**Issue by faxioman** [APSL/docker-thumbor#82]
As stated in nginx documentation for add_header (http://nginx.org/en/docs/http/ngx_http_headers_module.html):

`There could be several add_header directives. These directives are inherited from the previous level if and only if there are no add_header directives defined on the current level.`

Enabling AUTO_WEBP option an add_header directive is added at "location" level, overriding all the add_header directives at "server" level

**Comment by gingerlime** [comment]
@faxioman I just bumped into a similar issue at https://github.com/MinimalCompact/thumbor and the implementation there now supports both.
