### ISSUE TITLE
How to use in localhost?

### ISSUE THREAD

**Issue by roopemerikukka** [APSL/docker-thumbor#85]
Is there some easy way to use these images locally? I have a containerized website running on my machine and I have set domain for it to the host machines `/etc/hosts` like `127.0.0.1 dev.mysite.com`.

I also have the thumbor container running locally in address `dev.mythumbor.com` and nginx proxy container that listens hosts port 80 and automatically routes the domains to correct containers.

Now I would like to use the local version of thumbor inside the website like:
```html
<img src="http://dev.thumbor.com/unsafe/50x50/http://dev.mysite.com/image.jpg" />
```

But this gives me HTTP Error 504. If I'm on the right path this is happening because the thumbor container cannot resolve the domain set in host machines `/etc/hosts` but I havent figured out how to fix this issue.

I would like if someone has found some solution for this problem and perhaps even solution where I could have n amount of dev websites running and all of them using the same instance of thumbor without linking it to every website project separately.

**Comment by kkopachev** [comment]
is your nginx capable of serving that image, if requested directly? Like this: http://dev.mysite.com/image.jpg ?

If yes, you might want to add extra hosts to compose config
https://docs.docker.com/compose/compose-file/#extra_hosts

On the other hand, might be easier to make thumbor use file_loader and mount directory with your images into thumbor container. Then request it as http://dev.thumbor.com/unsafe/50x50/image.jpg

**Comment by otsybulsky** [comment]
Hi! I try `http://localhost:8000/unsafe/130x130/smart/localhost:4000/uploads/oYyDuINT1i.jpg`
error
2018-12-22 16:08:18 thumbor:WARNING ERROR retrieving image http://localhost:4000/uploads/oYyDuINT1i.jpg: [Errno 99] Cannot assign requested address
2018-12-22 16:08:18 tornado.access:ERROR 504 GET /unsafe/130x130/smart/localhost:4000/uploads/oYyDuINT1i.jpg (172.17.0.1) 34.94ms

docker config
docker run --rm --name thumbor \
  -p 8000:8000 \
  --add-host host:0.0.0.0 \
  -e RESULT_STORAGE_STORES_UNSAFE=True \
  -e LOADER='thumbor.loaders.file_loader_http_fallback' \
  -e DETECTORS="['thumbor.detectors.face_detector','thumbor.detectors.feature_detector']" \
  -e SECRET_KEY='secret' \
  -v `pwd`/thumbor-data:/data apsl/thumbor:latest

How i can use **localhost:4000**?

**Comment by roopemerikukka** [comment]
The localhost doesn't point to the host machine but to the docker container and thus it cannot be found. If the `localhost:4000` is also running inside docker container you can use the container name if they are in the same docker network.
