### ISSUE TITLE
simplification

### ISSUE THREAD

**Issue by gingerlime** [APSL/docker-thumbor#93]
Hi @eduherraiz. I've been looking at ways to simplify the repo / process. This is in line with [the list you created](https://github.com/APSL/docker-thumbor/issues/79#issuecomment-380208318).

I have a couple of questions however, at least to make sure I'm not missing anything important, and that I better understand some of the things you have in place already:

* I noticed that you use a docker-based pypi server and `wheelhouse` / `--use-wheel`. What's the reason for using it? Is it purely for performance reasons when building multiple docker images? (because the initial test build still pulls from pypi as far as I can tell). I'm wondering if the images are all based on one base, then there won't be a real need for this level of caching, because docker will provide it anyway, so that's one thing to potentially simplify. If, however, there's another / different reason, then I'm curious to know.
* What's the reason for having `test/builder`/ `Dockerfile.build`? Is it purely to "bake" pip packages into the wheelhouse? Or is there another reason?
* I can see the reason for using circus inside `thumbor-multiprocess`, but have you considered / are you open to using native docker/docker-compose scaling with something like [nginx-proxy](https://github.com/jwilder/nginx-proxy) or [traefik](https://traefik.io/) to handle load balancing across multiple thumbor containers. This has the benefit of simplifying things by having less types of images to build/maintain.

**Comment by drzraf** [comment]
traefik + alpine+python3 based image would be a nice change

**Comment by gingerlime** [comment]
The ideas here (and more) were implemented in https://github.com/MinimalCompact/thumbor

**Comment by eduherraiz** [comment]
Thank you for your comments @gingerlime 
The wheelhouse and old build system had the objective to reduce the size of the final image, trying to compile some huge packages and just share compiled with the final image with the wheels. Some of the packages for opencv and others had a lot of big build-dependencies.
In our new build system we removed all of this.

The thumbor-multiprocess image was prepared basically for some old enviroments where we can't use this proxy or orquestration tools. We really encourage to use the thumbor base image in all the moderns enviroments and we will just maintain the multiprocess image for historical reasons.

I'm closing this issue and I'll open another ones if we can take some of your work on the fork.
