### ISSUE TITLE
clear cache or storage

### ISSUE THREAD

**Issue by alexgoncharcherkassy** [APSL/docker-thumbor#95]
How to clear storage, because after few weeks using, disk space decreases very quickly. i am helped only remove container and docker volume prune.  Docker ran with env parameters ( --env STORAGE_EXPIRATION_SECONDS=1209600 --env RESULT_STORAGE_EXPIRATION_SECONDS=1209600 --env MAX_AGE_TEMP_IMAGE=86400)

**Comment by gingerlime** [comment]
We also bumped into a similar issue. We ended up reducing the expration times, as well as using a very simple monit container that checks for diskspace and clears it if it's too low.

i.e.

```
# docker-compose.yml
...
  monit:
    image: vimagick/monit
    volumes:
      - ./monit:/etc/monit
      - ./data:/data
```

and the monit folder has

```shell
$ tree monit/
monit/
├── conf.d
│   └── diskspace.cfg
└── monitrc

$ cat monit/monitrc
###############################################################################
## Monit control file
###############################################################################

set daemon  30
set logfile /dev/stdout
set pidfile /var/run/monit.pid
set idfile /var/lib/monit/monit.id
set statefile /var/lib/monit/monit.state
set eventqueue basedir /var/lib/monit/events slots 5000
include /etc/monit/conf.d/*.cfg

$ cat monit/conf.d/diskspace.cfg
check filesystem rootfs with path /data/
    if space usage > 90% then exec "/bin/sh -c 'find /data/result_storage/v2/ -mindepth 1 -mmin +60 |xargs rm -rf'"
```

This would check for low diskspace and clear files in your result storage. You can also adapt it to clear the storage folder, change thresholds etc.

Hope this helps :)

**Comment by eduherraiz** [comment]
thank you @gingerlime for the fish.
I think is better manage the cache in a separated way like you propose.
I'm closing this issue.
