### ISSUE TITLE
error from daemon in stream: Error grabbing logs: EOF

### ISSUE THREAD

**Issue by pythdasch** [APSL/docker-thumbor#99]
HI,

Since 1 month I'm having this error and can't resolve it . apsl/thumbor is throwing a 502 and when I try to check the logs I have this error : error from daemon in stream: Error grabbing logs: EOF 

 It appears that this is an error within the container of apsl. 

Does someone had this issue before? and know how to fix this ?

Thanks.

**Comment by gingerlime** [comment]
I don't think this project is actively maintained. Take a look at https://github.com/MinimalCompact/thumbor - maybe it helps solve your problem? Otherwise, feel free to open an issue with more details and I hope someone can help.
